/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'khamitovdm' at '1/11/17 1:57 AM' with Gradle 3.2.1
 *
 * @author khamitovdm, @date 1/11/17 1:57 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
